POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Produto 01",
    "description": "Descrição do Produto 01",
    "manufacturer": "XYZ Inc.",
    "category": "Eletrônicos",
    "price": 99.10,
    "available": true
}

###

GET http://localhost:3000/products
Content-Type: application/json

###

GET http://localhost:3000/products?search=Produto
Content-Type: application/json

###

GET http://localhost:3000/products/category?category=Eletrônicos
Content-Type: application/json

###

PUT http://localhost:3000/products/1cf83be5-9113-48b9-89d3-6c1a4281e196
Content-Type: application/json

{
    "name": "Produto 01 - Atualizado",
    "description": "Descrição do Produto 01",
    "manufacturer": "XYZ Inc.",
    "category": "Eletrônicos",
    "price": 99.10,
    "available": true
}

###

DELETE http://localhost:3000/products/1cf83be5-9113-48b9-89d3-6c1a4281e196
Content-Type: application/json